### ISSUE TITLE
When creating a plugin, the init script fails

### ISSUE THREAD

**Issue by codingmatty** [KELiON/create-cerebro-plugin#5]
Console Error: 
```
<dir>/cerebro/cerebro-plugin-convert/node_modules/cerebro-scripts/scripts/init.js:57
            throw err;
            ^

Error: ENOENT: no such file or directory, stat '<dir>/cerebro/cerebro-plugin-convert/npmignore'
    at Error (native)
error Command failed.
Exit code: 1
Command: ~/.config/yarn/global/node_modules/create-cerebro-plugin/index.js
Arguments: cerebro-plugin-convert
Directory: ~/cerebro
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

It seems to fail because `npmignore` doesn't exist... except for that when I opened the directory in my text editor, there indeed was an `npmignore` file, which I had to manually convert to `.npmignore`

**Comment by KELiON** [comment]
@codingmatty and is this directory correct: `/cerebro/cerebro-plugin-convert/npmignore`?

**Comment by lawgsy** [comment]
@KELiON  I can confirm this issue, the file `npmignore` **does exist** in the target directory **after** the error is thrown and yarn is finished (and so does `gitignore`, both without dot prefix).

```
04-12-2017  19:18    <DIR>          .
04-12-2017  19:18    <DIR>          ..
04-12-2017  19:18    <DIR>          dist
04-12-2017  19:17    <DIR>          node_modules
04-12-2017  19:17    <DIR>          src
04-12-2017  19:17               283 gitignore
04-12-2017  19:17                41 npmignore
04-12-2017  19:17               416 package.json
04-12-2017  19:17           156.143 yarn.lock
               4 File(s)        156.883 bytes
```

**Comment by weilbith** [comment]
Same here.
Btw: What should happen if I run `yarn start` in my fresh created plugin project? For me it do some outputs and then nothing happens. It does not close, no exception, just nothing. I expect that this must not have to do with my _NodeJS_ version, didn't it?

```
yarn start 
yarn run v1.3.2
warning You are using Node "7.10.0" which is not supported and may encounter bugs or unexpected behavior. Yarn supports the following semver range: "^4.8.0 || ^5.7.0 || ^6.2.2 || >=8.0.0"
warning package.json: No license field
$ cerebro-scripts start
Start plugin development
   Create symlink
   Starting webpack...

Webpack is watching the files…

Hash: be70195be7ae8aa8e233
Version: webpack 2.5.1
Time: 182ms
   Asset     Size  Chunks             Chunk Names
index.js  2.96 kB       0  [emitted]  index
   [0] ./src/index.js 130 bytes {0} [built]

```

**Comment by lawgsy** [comment]
Running `yarn start` in your plugin directory will build the plugin, create a symlink (or was this done during creation already?) so cerebro can load it and then start 'watching' the directory, building when necessary.

You can then open a cerebro instance, check your plugins and see your newly created plugin under Development at the top. Any changes will be immediately be picked up as long as you are running `yarn start` somewhere in the background as stated above.

You may need to reload (right click in taskbar>development>reload) to see the changes in plugin. Be sure to open the main Dev window if you cannot find your plugin, it may have an error and not have loaded

**Comment by weilbith** [comment]
@lawgsy
Thanks for this helpful answer. Will give it a try soon. 
What's about the missing `npmignore` file?

**Comment by lawgsy** [comment]
Using this repo to create a plugin should generate two files, `npmignore` and `gitignore`, but these should actually be generated as `.npmignore` and `.gitignore` instead (hence the renaming being done in a script in this repo, but the renaming fails for some reason - the files do not exist at the time at renaming).

If you are on Windows, you can rename the files using your code editor or command line:
`mv npmignore .npmignore && mv gitignore .gitignore`. You will probably not be able to rename them using the File Explorer because Windows does not like filenames with a dot as prefix much.

Your plugin should work without renaming them while developing, but you really should rename them manually in order to avoid issues down the line.

If the files are missing, this is what they should contain. **Please tell us though if they are missing, because whenever I do this they do exist.**

`.gitignore`:
```
# See https://help.github.com/ignore-files/ for more about ignoring files.

# dependencies
/node_modules

# testing
/coverage

# production
/dist

# misc
.DS_Store
.env.local
.env.development.local
.env.test.local
.env.production.local

npm-debug.log*
yarn-debug.log*
yarn-error.log*
```

`.npmignore`:
```
src
node_modules
screenshot.png
yarn.lock
```

**Comment by weilbith** [comment]
Ah. Than it is a simple problem. 
I'm aware about the 'dot-Problem' in the Windows explorer, but cause using Linux it should be an eye blink. 
Thanks for your help!

**Comment by KELiON** [comment]
There was an issue in order – script tried to rename files before they were copied from template path. Now it is ok!
