### ISSUE TITLE
Test locally before publish

### ISSUE THREAD

**Issue by weilbith** [KELiON/create-cerebro-plugin#6]
Hey,
When I started with my own plugin, using this here to init, how can I add it to my locally installed _cerebro_ and try it out?
In the plugin documentation it is mentioned to public it on _npm_ with the correct tags, so the _cerebro_  plugin manager can find it. Is there a way to first test it locally before publish?
Thanks for help! :)

**Comment by lawgsy** [comment]
As I mentioned in https://github.com/KELiON/create-cerebro-plugin/issues/5, whenever you create a plugin using this repository, and run it using `yarn start`, it will automagically be added to your Cerebro (by creating a symlink in your local plugin storage, pointing to your development directory).

While files are being watched by webpack (the 'window staying open without any error or so' you mentioned in the other thread) you can develop your plugin and see the changes.

Alternatively, you can run `yarn build` whenever you make a change to do an entire build of your plugin, and then observe the changes in Cerebro, but this will definitely slow down your development flow.
