### ISSUE TITLE
Add an option to build script to skip minification

### ISSUE THREAD

**Issue by KELiON** [KELiON/create-cerebro-plugin#9]
In some plugins minification breaks the code, in those plugins it makes sense to skip minification. Would be great to have an option to skip it in build script of cerebro-scripts, so user can update `build` script in package.json to `cerebro-scripts build --skip-minification`

**Comment by arnm** [comment]
any word on this? some packages im trying to import are coming back empty.

**Comment by KELiON** [comment]
@arnm can you share links? BTW this idea is not implemented yet

**Comment by ogustavo-pereira** [comment]
This issue is very old I will close it if we have more related topics we will open it
